# Generated by Django 6.0.3 on 2026-03-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Car Name")),
                ("brand", models.CharField(max_length=100, verbose_name="Brand")),
                ("model_year", models.PositiveIntegerField(verbose_name="Model Year")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hatchback", "Hatchback"),
                            ("sedan", "Sedan"),
                            ("suv", "SUV"),
                            ("luxury", "Luxury"),
                        ],
                        default="sedan",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("electric", "Electric"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="petrol",
                        max_length=20,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[("manual", "Manual"), ("automatic", "Automatic")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("seating_capacity", models.PositiveIntegerField(default=5)),
                (
                    "mileage",
                    models.CharField(
                        blank=True, help_text="e.g., 18 km/l", max_length=30
                    ),
                ),
                (
                    "engine_cc",
                    models.CharField(
                        blank=True, help_text="e.g., 1200cc", max_length=30
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50)),
                (
                    "price_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Price Per Day (₹)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True, help_text="Enter features separated by commas"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cars/",
                        verbose_name="Car Image",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Available"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Featured on Homepage"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        default="Newasa, Maharashtra",
                        max_length=200,
                        verbose_name="Pickup Location",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=15)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("booking", "Booking Help"),
                            ("complaint", "Complaint"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
